VERTICAL_TOP_SIZE = 500
VERTICAL_BOTTOM_SIZE = 500
HORIZONTAL_LEFT_SIZE = 300
HORIZONTAL_RIGHT_SIZE = 700

WIDTH_WIDGET = 300
WIDTH_WIDGET_RIGHT = 450

IMAGE_DIMENSION = 325

URL = "https://commons.wikimedia.org/w/api.php"